version: '3.8'
services:
  database:
    image: 'mongo'
    # container_name: 'mongoDB'
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=$DATABASE_NAME
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    ports: 
      - '27017:27017'
    volumes: 
      - $DATABASE_DATA_PATH:/data/db
  app:
    build: ./myApp
    restart: always
    environment:
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_HOST=$DATABASE_HOST