# Maintenant construisez une image pour la production !
# Inspirez-vous de votre précédente image docker




# Trick pour maintenir un processus actif et empêcher l'arrêt du container docker
ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]
